### ISSUE TITLE
`img src` maakt gebruik van een onduidelijke source

### ISSUE THREAD

**Issue by SamaraFellaDina** [lisagjh/the-startup#24]
https://github.com/lisagjh/the-startup/blob/847b84401b571b6108d7f89b03d5b0601b229575/index.html#L152

Er zitten spaties in de source. Dit kan je vervangen door:
`Caelor-Logos_Confluence-Lingo-AppIcon.svg`

**Comment by lisagjh** [comment]
als het goed is gefixt!
