### ISSUE TITLE
Font laad niet in

### ISSUE THREAD

**Issue by Remy2072** [lisagjh/the-startup#8]
Wanneer je naar de informatie tekst gaat krijg je het font times, probeer ook een tweede font toe te voegen als het eerste font niet in laad.

**Comment by lisagjh** [comment]
fixed, toegevoegd met fallback

https://github.com/lisagjh/the-startup/blob/7389eea16e6fe76125e91bc913dc337453d6d112/style/style.css#L103C1-L105C2
