### ISSUE TITLE
Compatability met Opera browser

### ISSUE THREAD

**Issue by KaanKalmi** [lisagjh/the-startup#9]
![image](https://github.com/lisagjh/the-startup/assets/144000125/a941ac09-296c-44d9-8f4d-9b22b5a65b93)

Ik heb gezien dat de buttons niet werken op mijn browser maar wel op de jouwe(firefox), Kijk ook ff hiernaar misschien -webkit gebruiken?

**Comment by lisagjh** [comment]
Hier ga ik voor nu even niks mee doen, is iets waar ik in een latere sprint wel meer over wil leren.

**Comment by KaanKalmi** [comment]
kijk eens naar css webkits misschien staat het daarin🤔
